
services:
  data_preprocessing:
    build: .
    command: python preprocess.py
    volumes:
      - ./data:/app/data
      - ./models:/app/models

  model_training:
    build: .
    command: python train_model.py
    volumes:
      - ./data:/app/data
      - ./models:/app/models
      - ./templates:/app/templates
    depends_on:
      - data_preprocessing

  web_app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./models:/app/models
      - ./templates:/app/templates
    depends_on:
      - model_training
    command: >
      sh -c "python app.py"
